# Generated by Django 5.0 on 2024-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredients",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="steps",
            name="steps",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
